AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  imageProcess

  Sample SAM Template for imageProcess

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  convertImage:
    Type: AWS::Serverless::Function
    Properties:
      Role: "arn:aws:iam::292597057072:role/LabRole"
      CodeUri: ./convertImage
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  compressImage:
    Type: AWS::Serverless::Function
    Properties:
      Role: "arn:aws:iam::292597057072:role/LabRole"
      CodeUri: ./compressImage
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  resizeImage:
    Type: AWS::Serverless::Function
    Properties:
      Role: "arn:aws:iam::292597057072:role/LabRole"
      CodeUri: ./resizeImage
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  detectLabels:
    Type: AWS::Serverless::Function
    Properties:
      Role: "arn:aws:iam::292597057072:role/LabRole"
      CodeUri: ./detectLabels
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
